echo "Setting environment variables for Terraform"
export ARM_CLIENT_ID="<Your SP ID>"
export ARM_CLIENT_SECRET="Your SP Password>"
export ARM_TENANT_ID="<Your Tenant ID>"
export ARM_SUBSCRIPTION_ID="<Your Subscription ID>"
export TF_VAR_rgtarget="<Target Resource Group>"
export TF_VAR_loctarget="<Target Location>"
